# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_collection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_collection.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14log_collection.proto\x12\x08tutorial\"\x12\n\x03Log\x12\x0b\n\x03log\x18\x01 \x01(\t\",\n\rLogCollection\x12\x1b\n\x04logs\x18\x01 \x03(\x0b\x32\r.tutorial.Logb\x06proto3'
)




_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='tutorial.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='tutorial.Log.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=52,
)


_LOGCOLLECTION = _descriptor.Descriptor(
  name='LogCollection',
  full_name='tutorial.LogCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='tutorial.LogCollection.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=98,
)

_LOGCOLLECTION.fields_by_name['logs'].message_type = _LOG
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['LogCollection'] = _LOGCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'log_collection_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Log)
  })
_sym_db.RegisterMessage(Log)

LogCollection = _reflection.GeneratedProtocolMessageType('LogCollection', (_message.Message,), {
  'DESCRIPTOR' : _LOGCOLLECTION,
  '__module__' : 'log_collection_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.LogCollection)
  })
_sym_db.RegisterMessage(LogCollection)


# @@protoc_insertion_point(module_scope)
